title = "Gitleaks config"
description = "Ignore false positives"
[[rules]]
id = "aws-access-key"
description = "Ignore AWS keys in virtual env"
regex = '''AKIA[A-Z0-9]{16}'''
paths = ["!django_web_app/.venv/.*"]
